### ISSUE TITLE
`get_database` keyword argument typo

### ISSUE THREAD

**Issue by westernwontons** [L0RD-ZER0/Motor-Types#13]
`AsyncIOMotorClient.get_database` has a `read_preference` keyword argument, which is mistyped as `read_preferences`, causing `pyright` type errors. According to the Motor docs, the word is singular. Reference:
https://motor.readthedocs.io/en/stable/api-asyncio/asyncio_motor_client.html?highlight=get_database#motor.motor_asyncio.AsyncIOMotorClient.get_database

**Comment by L0RD-ZER0** [comment]
I've verified the issue, and it should be a quick replace. And it seems it's not just this one place either. There's many more of these. I'll refer through the docs and fix anywhere applicable.

Thanks a lot for finding this one out! I'll fix it in something around 10-12 hours (tomorrow). Thanks for your contribution. Much appreciated!
