### ISSUE TITLE
`keys` in `create_index()` 

### ISSUE THREAD

**Issue by haoyun** [L0RD-ZER0/Motor-Types#16]
https://github.com/L0RD-ZER0/Motor-Types/blob/3c2ce3c7eb98ebc5b41cad351b9b72bf54af97ce/motor-stubs/core.pyi#L396-L402

The example in the documentation

```
my_collection.create_index([("mike", pymongo.DESCENDING),
                            "eliot"])
```

is an exception.

keys can be a list of `Union[tuple, str]` instead of only a list of `Union[Tuple]` (`_Index`).

**Comment by L0RD-ZER0** [comment]
Hmmmm, can also specify subtype in tuple as well then depending on how they do stuff, have to look into this more. Took a note of it. Thanks for notifying! Really appreciate your contribution!! Keep up the great work!

**Comment by L0RD-ZER0** [comment]
Going a little back, it becomes a ``Union[str, typing.Sequence[typing.Tuple[str, typing.Union[int, str, typing.Mapping[str, typing.Any]]]]]``, however that is comprehensible. Will add it to main branch and update in documentation branch (is local, haven't pushed yet).

**Comment by L0RD-ZER0** [comment]
Yep, will resolve this tomorrow! Thanks again for notifying about this!!

**Comment by L0RD-ZER0** [comment]
![image](https://github.com/L0RD-ZER0/Motor-Types/assets/68327382/0ab71aa6-ad2b-4296-abcb-7dfe56a557fc)


As you can see here, the final type for ``keys`` param that ``_Key_or_Index`` evaluates to is ``str | Sequence[tuple[str, int | str | Mapping[str, Any]]]``, which is the same thing what pymongo's hint ends up evaluating into, and it accepts the example you posted with no issues. So I'll be closing this one as completed. Do let me know if there are any other queries.

**Comment by L0RD-ZER0** [comment]
Did some more research, and from Motor 3.4, folks at MongoDB provide their own type hints and all, and use a different version of pymongo than (4.5+) than one being used in (4.1~4.3) or lower, which changed the types of ``_IndexKeyHint``. On a sidenote, since motor is providing typehints, might consider archiving this project. Do let me know your thoughts in further comments.

**Comment by haoyun** [comment]
Yes. Since Motor now has built-in typing, I think the project can be archived. Thanks for your efforts.

**Comment by L0RD-ZER0** [comment]
> Yes. Since Motor now has built-in typing, I think the project can be archived. Thanks for your efforts.

Same to you buddy, thanks for your contributions as well!
