### ISSUE TITLE
`.to_list(None)`

### ISSUE THREAD

**Issue by haoyun** [L0RD-ZER0/Motor-Types#2]
https://github.com/L0RD-ZER0/Motor-Types/blob/379b709157f524ff2b448ca4c28f34eb127a6441/motor-stubs/core.pyi#L734

https://motor.readthedocs.io/en/stable/api-tornado/cursors.html#motor.motor_tornado.MotorCommandCursor.to_list

**Comment by L0RD-ZER0** [comment]
I'll verify it in a bit. Thanks for finding out about this!

**Comment by L0RD-ZER0** [comment]
I merged the PR. Do let me know if you require this fix urgently or if it's alright that this sits on there for a bit until next patch to the stubs.
